-- 개발 DB(Oracle 19c, 스키마 dx) 전용 스키마. 운영 원천은 docs/spec/07_DBA_DDL.sql.
-- 07 에서 운영 전용 요소를 제거한 dev 변형: 테이블스페이스 절 / call_hist INTERVAL 파티션 /
-- DBMS_SCHEDULER 잡 / CREATE TABLESPACE·USER 제거. 현재 접속 스키마에 그대로 생성된다.
-- ⚠️ 07 이 바뀌면 본 파일도 함께 갱신(스키마 원천은 07). 재실행 시 ORA-00955(이미 존재)는 무시 가능.

-- ===== 시퀀스 (7) =====
CREATE SEQUENCE SEQ_DAILY_API_NO       START WITH 1 INCREMENT BY 1 NOCACHE NOORDER;
CREATE SEQUENCE SEQ_DAILY_CONTCT_SYST  START WITH 1 INCREMENT BY 1 NOCACHE NOORDER;
CREATE SEQUENCE SEQ_DAILY_DATA_SRC     START WITH 1 INCREMENT BY 1 NOCACHE NOORDER;
CREATE SEQUENCE SEQ_CALL_HIST          START WITH 1 INCREMENT BY 1 CACHE 100 NOORDER;
CREATE SEQUENCE SEQ_USER_APPR          START WITH 1 INCREMENT BY 1 CACHE 20  NOORDER;
CREATE SEQUENCE SEQ_REFRESH            START WITH 1 INCREMENT BY 1 CACHE 50  NOORDER;
CREATE SEQUENCE SEQ_DS_STAT            START WITH 1 INCREMENT BY 1 CACHE 100 NOORDER;

-- ===== 마스터 (1~8) =====
CREATE TABLE DXAPI_USR_USER_M (
  USER_ID VARCHAR2(20 BYTE) NOT NULL,
  PW_HASH VARCHAR2(100 BYTE) NOT NULL,
  USER_NM VARCHAR2(50 CHAR) NOT NULL,
  HP_NO VARCHAR2(20 BYTE) NOT NULL,
  EMAIL VARCHAR2(100 BYTE) NOT NULL,
  ORG_NM VARCHAR2(100 CHAR) NOT NULL,
  DEPT_NM VARCHAR2(100 CHAR) NOT NULL,
  TEL_NO VARCHAR2(20 BYTE),
  ROLE_DVCD VARCHAR2(10 BYTE) NOT NULL,
  STTUS_DVCD VARCHAR2(10 BYTE) NOT NULL,
  LTLY_LOGIN_DT TIMESTAMP,
  LOGIN_FAILURE_TMCNT NUMBER(2) DEFAULT 0 NOT NULL,
  REGID VARCHAR2(20 BYTE), REGDT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, REGIP VARCHAR2(50 BYTE),
  MODID VARCHAR2(20 BYTE), MODDT TIMESTAMP, MODIP VARCHAR2(50 BYTE),
  CONSTRAINT PK_USR_USER PRIMARY KEY (USER_ID),
  CONSTRAINT CK_USR_USER_ROLE CHECK (ROLE_DVCD IN ('ADMIN','USER','AI')),
  CONSTRAINT CK_USR_USER_STTUS CHECK (STTUS_DVCD IN ('PENDING','ACTIVE','REJECTED','INACTIVE'))
);
CREATE UNIQUE INDEX UX_USR_USER_EMAIL ON DXAPI_USR_USER_M (EMAIL);
CREATE INDEX IX_USR_USER_STTUS ON DXAPI_USR_USER_M (STTUS_DVCD);

CREATE TABLE DXAPI_USR_EXT_SYS_M (
  CONTCT_SYST_ID VARCHAR2(20 BYTE) NOT NULL,
  CONTCT_SYST_NM VARCHAR2(100 CHAR) NOT NULL,
  CRTFC_KEY_HASH VARCHAR2(200 BYTE) NOT NULL,
  CRTFC_KEY_DISTI_TEXT VARCHAR2(8 BYTE) NOT NULL,
  ALW_IP_ADDR_TEXT CLOB NOT NULL,
  USE_BEGIN_DT TIMESTAMP NOT NULL,
  USE_END_DT TIMESTAMP NOT NULL,
  PICG_NM VARCHAR2(50 CHAR), PICG_TEL_NO VARCHAR2(20 BYTE), PICG_EMAIL VARCHAR2(100 BYTE),
  RMARK VARCHAR2(2000 CHAR),
  STTUS_DVCD VARCHAR2(10 BYTE) NOT NULL,
  RATE_LMT_PER_MIN NUMBER(6),
  REGID VARCHAR2(20 BYTE), REGDT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, REGIP VARCHAR2(50 BYTE),
  MODID VARCHAR2(20 BYTE), MODDT TIMESTAMP, MODIP VARCHAR2(50 BYTE),
  CONSTRAINT PK_EXT_SYS PRIMARY KEY (CONTCT_SYST_ID),
  CONSTRAINT CK_EXT_SYS_STTUS CHECK (STTUS_DVCD IN ('ACTIVE','INACTIVE')),
  CONSTRAINT CK_EXT_SYS_PERIOD CHECK (USE_BEGIN_DT <= USE_END_DT),
  CONSTRAINT CK_EXT_SYS_RATE CHECK (RATE_LMT_PER_MIN IS NULL OR RATE_LMT_PER_MIN >= 0),
  CONSTRAINT CK_EXT_SYS_IP_JSON CHECK (ALW_IP_ADDR_TEXT IS JSON)
);
CREATE INDEX IX_EXT_SYS_KEY_DISTI ON DXAPI_USR_EXT_SYS_M (CRTFC_KEY_DISTI_TEXT);
CREATE INDEX IX_EXT_SYS_USE_END ON DXAPI_USR_EXT_SYS_M (USE_END_DT);

CREATE TABLE DXAPI_DATASOURCE_M (
  DATA_SRC_ID VARCHAR2(20 BYTE) NOT NULL,
  DATA_SRC_NM VARCHAR2(100 CHAR) NOT NULL,
  DB_TYPE_DVCD VARCHAR2(10 BYTE) NOT NULL,
  JDBC_URL VARCHAR2(500 BYTE) NOT NULL,
  DB_USER_ID VARCHAR2(50 BYTE) NOT NULL,
  DB_ENC_PW VARCHAR2(500 BYTE) NOT NULL,
  MINI_POOL_CNT NUMBER(3) DEFAULT 5 NOT NULL,
  MAX_POOL_CNT NUMBER(3) DEFAULT 20 NOT NULL,
  QUERY_TIMEOUT_SEC NUMBER(3) DEFAULT 10 NOT NULL,
  CONN_TIMEOUT_MS NUMBER(6) DEFAULT 30000 NOT NULL,
  USE_YN CHAR(1) DEFAULT 'Y' NOT NULL,
  REGID VARCHAR2(20 BYTE), REGDT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, REGIP VARCHAR2(50 BYTE),
  MODID VARCHAR2(20 BYTE), MODDT TIMESTAMP, MODIP VARCHAR2(50 BYTE),
  CONSTRAINT PK_DATA_SRC PRIMARY KEY (DATA_SRC_ID),
  CONSTRAINT CK_DATA_SRC_TYPE CHECK (DB_TYPE_DVCD IN ('ORACLE','POSTGRES','MYSQL')),
  CONSTRAINT CK_DATA_SRC_USE CHECK (USE_YN IN ('Y','N')),
  CONSTRAINT CK_DATA_SRC_POOL CHECK (MINI_POOL_CNT >= 0 AND MAX_POOL_CNT >= MINI_POOL_CNT)
);
CREATE UNIQUE INDEX UX_DATA_SRC_NM ON DXAPI_DATASOURCE_M (DATA_SRC_NM);

CREATE TABLE DXAPI_API_DEF_M (
  API_NO VARCHAR2(20 BYTE) NOT NULL,
  API_NM VARCHAR2(200 CHAR) NOT NULL,
  API_GROUP_CD VARCHAR2(20 BYTE) NOT NULL,
  HTTP_MTHD_DVCD VARCHAR2(10 BYTE) NOT NULL,
  REQ_PATH VARCHAR2(200 BYTE) NOT NULL,
  STTUS_DVCD VARCHAR2(10 BYTE) NOT NULL,
  DATA_SRC_ID VARCHAR2(20 BYTE) NOT NULL,
  AUTH_ESSNTL_YN CHAR(1) DEFAULT 'Y' NOT NULL,
  DOC_DISP_YN CHAR(1) DEFAULT 'Y' NOT NULL,
  SQL_TEXT CLOB NOT NULL,
  QUERY_TIMEOUT_SEC NUMBER(3),
  DESC_TEXT VARCHAR2(2000 CHAR),
  REGID VARCHAR2(20 BYTE), REGDT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, REGIP VARCHAR2(50 BYTE),
  MODID VARCHAR2(20 BYTE), MODDT TIMESTAMP, MODIP VARCHAR2(50 BYTE),
  CONSTRAINT PK_API_DEF PRIMARY KEY (API_NO),
  CONSTRAINT FK_API_DEF_DATA_SRC FOREIGN KEY (DATA_SRC_ID) REFERENCES DXAPI_DATASOURCE_M (DATA_SRC_ID),
  CONSTRAINT CK_API_DEF_MTHD CHECK (HTTP_MTHD_DVCD IN ('GET','POST','PUT','DELETE')),
  CONSTRAINT CK_API_DEF_STTUS CHECK (STTUS_DVCD IN ('DRAFT','ACTIVE','INACTIVE')),
  CONSTRAINT CK_API_DEF_AUTH CHECK (AUTH_ESSNTL_YN IN ('Y','N')),
  CONSTRAINT CK_API_DEF_DOC CHECK (DOC_DISP_YN IN ('Y','N'))
);
CREATE UNIQUE INDEX UX_API_DEF_REQ_PATH ON DXAPI_API_DEF_M (REQ_PATH);
CREATE INDEX IX_API_DEF_GROUP_STTUS ON DXAPI_API_DEF_M (API_GROUP_CD, STTUS_DVCD);
CREATE INDEX IX_API_DEF_DATA_SRC ON DXAPI_API_DEF_M (DATA_SRC_ID);

CREATE TABLE DXAPI_API_PARAM_M (
  API_NO VARCHAR2(20 BYTE) NOT NULL,
  PARAM_SEQ NUMBER(3) NOT NULL,
  PARAM_NM VARCHAR2(50 BYTE) NOT NULL,
  PARAM_TYPE_DVCD VARCHAR2(20 BYTE) NOT NULL,
  ESSNTL_YN CHAR(1) DEFAULT 'N' NOT NULL,
  BAS_VAL VARCHAR2(200 CHAR),
  DESC_TEXT VARCHAR2(500 CHAR),
  MASK_RULE_DVCD VARCHAR2(20 BYTE) DEFAULT 'none' NOT NULL,
  REGID VARCHAR2(20 BYTE), REGDT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, MODID VARCHAR2(20 BYTE), MODDT TIMESTAMP,
  CONSTRAINT PK_API_PARAM PRIMARY KEY (API_NO, PARAM_SEQ),
  CONSTRAINT FK_API_PARAM_API FOREIGN KEY (API_NO) REFERENCES DXAPI_API_DEF_M (API_NO) ON DELETE CASCADE,
  CONSTRAINT CK_API_PARAM_TYPE CHECK (PARAM_TYPE_DVCD IN ('string','number','date','boolean')),
  CONSTRAINT CK_API_PARAM_ESS CHECK (ESSNTL_YN IN ('Y','N')),
  CONSTRAINT CK_API_PARAM_MASK CHECK (MASK_RULE_DVCD IN ('none','name','phone','email','rrn','card','addr'))
);

CREATE TABLE DXAPI_API_RESP_M (
  API_NO VARCHAR2(20 BYTE) NOT NULL,
  RSPNS_SEQ NUMBER(3) NOT NULL,
  COL_NM VARCHAR2(50 BYTE) NOT NULL,
  COL_TYPE_DVCD VARCHAR2(20 BYTE) NOT NULL,
  DISP_NM VARCHAR2(100 CHAR),
  MASK_RULE_DVCD VARCHAR2(20 BYTE) DEFAULT 'none' NOT NULL,
  REGID VARCHAR2(20 BYTE), REGDT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, MODID VARCHAR2(20 BYTE), MODDT TIMESTAMP,
  CONSTRAINT PK_API_RESP PRIMARY KEY (API_NO, RSPNS_SEQ),
  CONSTRAINT FK_API_RESP_API FOREIGN KEY (API_NO) REFERENCES DXAPI_API_DEF_M (API_NO) ON DELETE CASCADE,
  CONSTRAINT CK_API_RESP_MASK CHECK (MASK_RULE_DVCD IN ('none','name','phone','email','rrn','card','addr'))
);

CREATE TABLE DXAPI_EXT_SYS_API_MAP_M (
  CONTCT_SYST_ID VARCHAR2(20 BYTE) NOT NULL,
  API_NO VARCHAR2(20 BYTE) NOT NULL,
  MAP_DT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  REGID VARCHAR2(20 BYTE), REGDT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, REGIP VARCHAR2(50 BYTE),
  CONSTRAINT PK_EXT_SYS_API_MAP PRIMARY KEY (CONTCT_SYST_ID, API_NO),
  CONSTRAINT FK_MAP_EXT_SYS FOREIGN KEY (CONTCT_SYST_ID) REFERENCES DXAPI_USR_EXT_SYS_M (CONTCT_SYST_ID) ON DELETE CASCADE,
  CONSTRAINT FK_MAP_API FOREIGN KEY (API_NO) REFERENCES DXAPI_API_DEF_M (API_NO) ON DELETE CASCADE
);
CREATE INDEX IX_EXT_SYS_API_MAP_API ON DXAPI_EXT_SYS_API_MAP_M (API_NO);

CREATE TABLE DXAPI_USR_EXT_SYS_USER_M (
  CONTCT_SYST_ID VARCHAR2(20 BYTE) NOT NULL,
  USER_ID VARCHAR2(20 BYTE) NOT NULL,
  SYST_ROLE_DVCD VARCHAR2(20 BYTE) DEFAULT 'MEMBER' NOT NULL,
  REGID VARCHAR2(20 BYTE), REGDT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_USR_EXT_SYS_USER PRIMARY KEY (CONTCT_SYST_ID, USER_ID),
  CONSTRAINT FK_USR_EXT_SYS_USER_SYS FOREIGN KEY (CONTCT_SYST_ID) REFERENCES DXAPI_USR_EXT_SYS_M (CONTCT_SYST_ID) ON DELETE CASCADE,
  CONSTRAINT FK_USR_EXT_SYS_USER_USR FOREIGN KEY (USER_ID) REFERENCES DXAPI_USR_USER_M (USER_ID) ON DELETE CASCADE,
  CONSTRAINT CK_USR_EXT_SYS_USER_ROLE CHECK (SYST_ROLE_DVCD IN ('OWNER','MEMBER'))
);
CREATE INDEX IX_USR_EXT_SYS_USER_USR ON DXAPI_USR_EXT_SYS_USER_M (USER_ID);

-- ===== 이력/승인/코드 (9~11) — call_hist 는 dev 라 비파티션 일반 테이블 =====
CREATE TABLE DXAPI_CALL_HIST_L (
  HIST_SEQ NUMBER(18) NOT NULL,
  CALNG_DT TIMESTAMP(3) NOT NULL,
  CONTCT_SYST_ID VARCHAR2(20 BYTE),
  API_NO VARCHAR2(20 BYTE),
  REQ_PATH VARCHAR2(200 BYTE) NOT NULL,
  HTTP_MTHD_DVCD VARCHAR2(10 BYTE) NOT NULL,
  CLIENT_IP_ADDR VARCHAR2(50 BYTE) NOT NULL,
  TRC_ID VARCHAR2(50 BYTE) NOT NULL,
  PARAM_JSON_TEXT CLOB,
  RSPNS_STTUS_CD NUMBER(3) NOT NULL,
  ERR_CD VARCHAR2(50 BYTE),
  INTE_MS NUMBER(7) NOT NULL,
  REGDT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_CALL_HIST PRIMARY KEY (CALNG_DT, HIST_SEQ)
);
CREATE INDEX IX_CALL_HIST_AT ON DXAPI_CALL_HIST_L (CALNG_DT);
CREATE INDEX IX_CALL_HIST_API ON DXAPI_CALL_HIST_L (API_NO, CALNG_DT);
CREATE INDEX IX_CALL_HIST_STTUS ON DXAPI_CALL_HIST_L (RSPNS_STTUS_CD, CALNG_DT);
CREATE INDEX IX_CALL_HIST_TRC ON DXAPI_CALL_HIST_L (TRC_ID);
CREATE INDEX IX_CALL_HIST_EXT ON DXAPI_CALL_HIST_L (CONTCT_SYST_ID, CALNG_DT);

CREATE TABLE DXAPI_USER_APPR_L (
  CONFM_SEQ NUMBER(18) NOT NULL,
  CONFM_TYPE_DVCD VARCHAR2(20 BYTE) NOT NULL,
  TARGT_ID VARCHAR2(50 BYTE) NOT NULL,
  APLCNT_ID VARCHAR2(20 BYTE) NOT NULL,
  CONFMR_ID VARCHAR2(20 BYTE),
  STTUS_DVCD VARCHAR2(20 BYTE) NOT NULL,
  REASON VARCHAR2(2000 CHAR),
  APPL_DT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  PROC_DT TIMESTAMP,
  REGID VARCHAR2(20 BYTE), REGDT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, REGIP VARCHAR2(50 BYTE),
  MODID VARCHAR2(20 BYTE), MODDT TIMESTAMP, MODIP VARCHAR2(50 BYTE),
  CONSTRAINT PK_USER_APPR PRIMARY KEY (CONFM_SEQ),
  CONSTRAINT CK_USER_APPR_TYPE CHECK (CONFM_TYPE_DVCD IN ('USER_SIGNUP','API_USAGE')),
  CONSTRAINT CK_USER_APPR_STTUS CHECK (STTUS_DVCD IN ('PENDING','APPROVED','REJECTED'))
);
CREATE INDEX IX_USER_APPR_STTUS ON DXAPI_USER_APPR_L (STTUS_DVCD, APPL_DT);
CREATE INDEX IX_USER_APPR_TARGT ON DXAPI_USER_APPR_L (TARGT_ID);
CREATE INDEX IX_USER_APPR_APLCT ON DXAPI_USER_APPR_L (APLCNT_ID);

CREATE TABLE DXAPI_EZ_CODE_M (
  CLA_DVCD VARCHAR2(20 BYTE) NOT NULL,
  CD VARCHAR2(20 BYTE) NOT NULL,
  CD_NM VARCHAR2(100 CHAR) NOT NULL,
  USE_YN CHAR(1) DEFAULT 'Y' NOT NULL,
  SORT_SEQ NUMBER(3) DEFAULT 0 NOT NULL,
  DESC_TEXT VARCHAR2(500 CHAR),
  REGID VARCHAR2(20 BYTE), REGDT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, MODID VARCHAR2(20 BYTE), MODDT TIMESTAMP,
  CONSTRAINT PK_EZ_CODE PRIMARY KEY (CLA_DVCD, CD),
  CONSTRAINT CK_EZ_CODE_USE CHECK (USE_YN IN ('Y','N'))
);

-- ===== 신규 (12~14) =====
CREATE TABLE DXAPI_REFRESH_TOKEN_L (
  RFRSH_SEQ NUMBER(18) NOT NULL,
  JTI VARCHAR2(40 BYTE) NOT NULL,
  USER_ID VARCHAR2(20 BYTE) NOT NULL,
  ISSUE_DT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  EXPRE_DT TIMESTAMP NOT NULL,
  REVOKE_DT TIMESTAMP,
  REVOKE_REASON VARCHAR2(100 BYTE),
  ISSUE_IP_ADDR VARCHAR2(50 BYTE),
  USER_AGENT VARCHAR2(500 BYTE),
  CONSTRAINT PK_REFRESH_TOKEN PRIMARY KEY (RFRSH_SEQ),
  CONSTRAINT UX_REFRESH_TOKEN_JTI UNIQUE (JTI),
  CONSTRAINT FK_REFRESH_TOKEN_USR FOREIGN KEY (USER_ID) REFERENCES DXAPI_USR_USER_M (USER_ID) ON DELETE CASCADE
);
CREATE INDEX IX_REFRESH_TOKEN_USR_EXP ON DXAPI_REFRESH_TOKEN_L (USER_ID, EXPRE_DT);
CREATE INDEX IX_REFRESH_TOKEN_EXP ON DXAPI_REFRESH_TOKEN_L (EXPRE_DT);

CREATE TABLE DXAPI_API_DOC_CACHE_M (
  CACHE_KEY VARCHAR2(50 BYTE) NOT NULL,
  SPEC_VERSION VARCHAR2(10 BYTE) NOT NULL,
  SPEC_JSON CLOB NOT NULL,
  SPEC_HASH VARCHAR2(64 BYTE) NOT NULL,
  GENRT_DT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  SOURCE_API_CNT NUMBER(5) NOT NULL,
  CONSTRAINT PK_API_DOC_CACHE PRIMARY KEY (CACHE_KEY),
  CONSTRAINT CK_API_DOC_CACHE_JSON CHECK (SPEC_JSON IS JSON)
);

CREATE TABLE DXAPI_DS_RUNTIME_STAT_L (
  STAT_SEQ NUMBER(18) NOT NULL,
  DATA_SRC_ID VARCHAR2(20 BYTE) NOT NULL,
  SNAPSHOT_DT TIMESTAMP NOT NULL,
  POOL_ACTV_CNT NUMBER(4) NOT NULL,
  POOL_IDLE_CNT NUMBER(4) NOT NULL,
  POOL_MAX_CNT NUMBER(4) NOT NULL,
  POOL_USAGE_PCT NUMBER(3) NOT NULL,
  LTNCY_AVG_MS NUMBER(7),
  LTNCY_P95_MS NUMBER(7),
  ERR_CNT_1M NUMBER(7) DEFAULT 0 NOT NULL,
  STTUS_DVCD VARCHAR2(10 BYTE) NOT NULL,
  CONSTRAINT PK_DS_STAT PRIMARY KEY (STAT_SEQ),
  CONSTRAINT FK_DS_STAT_SRC FOREIGN KEY (DATA_SRC_ID) REFERENCES DXAPI_DATASOURCE_M (DATA_SRC_ID) ON DELETE CASCADE,
  CONSTRAINT CK_DS_STAT_STT CHECK (STTUS_DVCD IN ('정상','주의','심각')),
  CONSTRAINT CK_DS_STAT_PCT CHECK (POOL_USAGE_PCT BETWEEN 0 AND 100)
);
CREATE INDEX IX_DS_STAT_SRC_DT ON DXAPI_DS_RUNTIME_STAT_L (DATA_SRC_ID, SNAPSHOT_DT);
CREATE INDEX IX_DS_STAT_DT ON DXAPI_DS_RUNTIME_STAT_L (SNAPSHOT_DT);

-- ===== 공통 코드 시드 (07 §6 과 동일 31건) =====
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('USER_STTUS_DVCD','PENDING','대기',1,'회원가입 승인 대기');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('USER_STTUS_DVCD','ACTIVE','정상',2,'활성 사용자');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('USER_STTUS_DVCD','REJECTED','반려',3,'관리자 반려');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('USER_STTUS_DVCD','INACTIVE','비활성',4,'비활성 처리');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('API_STTUS_DVCD','DRAFT','임시저장',1,'미활성 API');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('API_STTUS_DVCD','ACTIVE','정상',2,'서비스 중');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('API_STTUS_DVCD','INACTIVE','비활성',3,'수동 중지');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('EXT_SYS_STTUS_DVCD','ACTIVE','정상',1,'서비스 중');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('EXT_SYS_STTUS_DVCD','INACTIVE','비활성',2,'중지');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ) VALUES ('ROLE_DVCD','ADMIN','관리자',1);
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ) VALUES ('ROLE_DVCD','USER','일반사용자',2);
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('ROLE_DVCD','AI','AI 서비스계정',3,'MCP 도구용. API 초안(DRAFT) 생성·메타 조회 전용. 활성화 권한 없음.');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ) VALUES ('DB_TYPE_DVCD','ORACLE','Oracle 19c',1);
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ) VALUES ('DB_TYPE_DVCD','POSTGRES','PostgreSQL 14+',2);
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ) VALUES ('DB_TYPE_DVCD','MYSQL','MySQL 8+',3);
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ) VALUES ('HTTP_MTHD_DVCD','GET','조회',1);
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ) VALUES ('HTTP_MTHD_DVCD','POST','등록/실행',2);
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ) VALUES ('HTTP_MTHD_DVCD','PUT','수정',3);
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ) VALUES ('HTTP_MTHD_DVCD','DELETE','삭제',4);
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('MASK_RULE_DVCD','none','없음',1,'마스킹 미적용');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('MASK_RULE_DVCD','name','이름',2,'첫 글자 외 *');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('MASK_RULE_DVCD','phone','핸드폰',3,'가운데 4자리 *');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('MASK_RULE_DVCD','email','이메일',4,'@ 앞 절반 *');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('MASK_RULE_DVCD','rrn','주민등록번호',5,'뒷 7자리 *');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('MASK_RULE_DVCD','card','카드번호',6,'가운데 8자리 *');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('MASK_RULE_DVCD','addr','주소',7,'동/번지 이후 *');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ) VALUES ('CONFM_TYPE_DVCD','USER_SIGNUP','회원가입 승인',1);
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ) VALUES ('CONFM_TYPE_DVCD','API_USAGE','API 사용 신청 승인',2);
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ) VALUES ('CONFM_STTUS_DVCD','PENDING','대기',1);
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ) VALUES ('CONFM_STTUS_DVCD','APPROVED','승인',2);
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ) VALUES ('CONFM_STTUS_DVCD','REJECTED','반려',3);
COMMIT;
