-- 공통 코드 시드 (DXAPI_EZ_CODE_M). 출처: doc/.../06_DB_모델링.md §7. DXAPI 스키마로 실행.
-- DDL(07_DBA_DDL.sql) 적용 후 1회 실행.

INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('USER_STTUS_DVCD',    'PENDING',  '대기',     1, '회원가입 승인 대기');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('USER_STTUS_DVCD',    'ACTIVE',   '정상',     2, '활성 사용자');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('USER_STTUS_DVCD',    'REJECTED', '반려',     3, '관리자 반려');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('USER_STTUS_DVCD',    'INACTIVE', '비활성',   4, '비활성 처리');

INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('API_STTUS_DVCD',     'DRAFT',    '임시저장', 1, '미활성 API');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('API_STTUS_DVCD',     'ACTIVE',   '정상',     2, '서비스 중');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('API_STTUS_DVCD',     'INACTIVE', '비활성',   3, '수동 중지');

INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('EXT_SYS_STTUS_DVCD', 'ACTIVE',   '정상',     1, '서비스 중');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('EXT_SYS_STTUS_DVCD', 'INACTIVE', '비활성',   2, '중지');

INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ) VALUES ('ROLE_DVCD', 'ADMIN', '관리자',    1);
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ) VALUES ('ROLE_DVCD', 'USER',  '일반사용자', 2);

INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ) VALUES ('DB_TYPE_DVCD', 'ORACLE',   'Oracle 19c',     1);
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ) VALUES ('DB_TYPE_DVCD', 'POSTGRES', 'PostgreSQL 14+', 2);
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ) VALUES ('DB_TYPE_DVCD', 'MYSQL',    'MySQL 8+',       3);

INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ) VALUES ('HTTP_MTHD_DVCD', 'GET',    '조회',     1);
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ) VALUES ('HTTP_MTHD_DVCD', 'POST',   '등록/실행', 2);
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ) VALUES ('HTTP_MTHD_DVCD', 'PUT',    '수정',     3);
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ) VALUES ('HTTP_MTHD_DVCD', 'DELETE', '삭제',     4);

INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('MASK_RULE_DVCD', 'none',  '없음',         1, '마스킹 미적용');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('MASK_RULE_DVCD', 'name',  '이름',         2, '첫 글자 외 *');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('MASK_RULE_DVCD', 'phone', '핸드폰',       3, '가운데 4자리 *');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('MASK_RULE_DVCD', 'email', '이메일',       4, '@ 앞 절반 *');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('MASK_RULE_DVCD', 'rrn',   '주민등록번호', 5, '뒷 7자리 *');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('MASK_RULE_DVCD', 'card',  '카드번호',     6, '가운데 8자리 *');
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ, DESC_TEXT) VALUES ('MASK_RULE_DVCD', 'addr',  '주소',         7, '동/번지 이후 *');

INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ) VALUES ('CONFM_TYPE_DVCD', 'USER_SIGNUP', '회원가입 승인',     1);
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ) VALUES ('CONFM_TYPE_DVCD', 'API_USAGE',   'API 사용 신청 승인', 2);

INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ) VALUES ('CONFM_STTUS_DVCD', 'PENDING',  '대기', 1);
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ) VALUES ('CONFM_STTUS_DVCD', 'APPROVED', '승인', 2);
INSERT INTO DXAPI_EZ_CODE_M (CLA_DVCD, CD, CD_NM, SORT_SEQ) VALUES ('CONFM_STTUS_DVCD', 'REJECTED', '반려', 3);

COMMIT;
