-- 메타 데모 시드. 출처: mockup/lib/mockData.ts (사용자 제외 — 사용자는 LocalDataSeeder 가 bcrypt 로 주입).
-- DDL(docs/spec/07_DBA_DDL.sql) + seed-codes.sql 적용 후 DXAPI 스키마로 실행. 게이트웨이(M3) 데모 데이터.

-- 1) 데이터소스
INSERT INTO DXAPI_DATASOURCE_M (DATA_SRC_ID, DATA_SRC_NM, DB_TYPE_DVCD, JDBC_URL, DB_USER_ID, DB_ENC_PW, MINI_POOL_CNT, MAX_POOL_CNT, QUERY_TIMEOUT_SEC, REGID)
VALUES ('DS20260509001', 'DAU-CORE-PROD', 'ORACLE',   'jdbc:oracle:thin:@core-prd.donga.ac.kr:1521/CORE', 'dxapi', 'ENC:seed-placeholder', 5, 50, 5, 'seed');
INSERT INTO DXAPI_DATASOURCE_M (DATA_SRC_ID, DATA_SRC_NM, DB_TYPE_DVCD, JDBC_URL, DB_USER_ID, DB_ENC_PW, MINI_POOL_CNT, MAX_POOL_CNT, QUERY_TIMEOUT_SEC, REGID)
VALUES ('DS20260509002', 'DAU-LMS-PROD',  'ORACLE',   'jdbc:oracle:thin:@lms-prd.donga.ac.kr:1521/LMS',  'dxapi', 'ENC:seed-placeholder', 5, 50, 5, 'seed');
INSERT INTO DXAPI_DATASOURCE_M (DATA_SRC_ID, DATA_SRC_NM, DB_TYPE_DVCD, JDBC_URL, DB_USER_ID, DB_ENC_PW, MINI_POOL_CNT, MAX_POOL_CNT, QUERY_TIMEOUT_SEC, REGID)
VALUES ('DS20260509003', 'DAU-LIB-PROD',  'POSTGRES', 'jdbc:postgresql://lib-prd:5432/library',          'dxapi', 'ENC:seed-placeholder', 3, 30, 5, 'seed');
INSERT INTO DXAPI_DATASOURCE_M (DATA_SRC_ID, DATA_SRC_NM, DB_TYPE_DVCD, JDBC_URL, DB_USER_ID, DB_ENC_PW, MINI_POOL_CNT, MAX_POOL_CNT, QUERY_TIMEOUT_SEC, REGID)
VALUES ('DS20260509004', 'DAU-HR-PROD',   'POSTGRES', 'jdbc:postgresql://hr-prd:5432/hr',                'dxapi', 'ENC:seed-placeholder', 3, 30, 5, 'seed');
INSERT INTO DXAPI_DATASOURCE_M (DATA_SRC_ID, DATA_SRC_NM, DB_TYPE_DVCD, JDBC_URL, DB_USER_ID, DB_ENC_PW, MINI_POOL_CNT, MAX_POOL_CNT, QUERY_TIMEOUT_SEC, REGID)
VALUES ('DS20260509005', 'DAU-CORE-STG',  'ORACLE',   'jdbc:oracle:thin:@core-stg.donga.ac.kr:1521/CORE', 'dxapi', 'ENC:seed-placeholder', 1, 20, 5, 'seed');

-- 2) API 정의
INSERT INTO DXAPI_API_DEF_M (API_NO, API_NM, API_GROUP_CD, HTTP_MTHD_DVCD, REQ_PATH, STTUS_DVCD, DATA_SRC_ID, AUTH_ESSNTL_YN, DOC_DISP_YN, SQL_TEXT, REGID)
VALUES ('A20260509001', '사용자 정보 조회', 'USER',  'GET',  'sample-user-info',  'ACTIVE', 'DS20260509001', 'Y', 'Y', 'SELECT user_id, user_nm, dept_nm FROM v_user WHERE user_id = #{id}', 'seed');
INSERT INTO DXAPI_API_DEF_M (API_NO, API_NM, API_GROUP_CD, HTTP_MTHD_DVCD, REQ_PATH, STTUS_DVCD, DATA_SRC_ID, AUTH_ESSNTL_YN, DOC_DISP_YN, SQL_TEXT, REGID)
VALUES ('A20260509002', '성적 목록 조회',   'GRADE', 'GET',  'sample-grade-list', 'ACTIVE', 'DS20260509001', 'Y', 'Y', 'SELECT subject, grade, semester FROM v_grade WHERE user_id = #{id}', 'seed');
INSERT INTO DXAPI_API_DEF_M (API_NO, API_NM, API_GROUP_CD, HTTP_MTHD_DVCD, REQ_PATH, STTUS_DVCD, DATA_SRC_ID, AUTH_ESSNTL_YN, DOC_DISP_YN, SQL_TEXT, REGID)
VALUES ('A20260509003', '성적 저장',        'GRADE', 'POST', 'sample-grade-save', 'ACTIVE', 'DS20260509001', 'Y', 'Y', 'INSERT INTO grade (user_id, subject, grade) VALUES (#{id}, #{subject}, #{grade})', 'seed');
INSERT INTO DXAPI_API_DEF_M (API_NO, API_NM, API_GROUP_CD, HTTP_MTHD_DVCD, REQ_PATH, STTUS_DVCD, DATA_SRC_ID, AUTH_ESSNTL_YN, DOC_DISP_YN, SQL_TEXT, REGID)
VALUES ('A20260509004', '부서 트리 조회',   'DEPT',  'GET',  'sample-dept-tree',  'ACTIVE', 'DS20260509001', 'Y', 'Y', 'SELECT id, name, parent_id FROM v_dept', 'seed');
INSERT INTO DXAPI_API_DEF_M (API_NO, API_NM, API_GROUP_CD, HTTP_MTHD_DVCD, REQ_PATH, STTUS_DVCD, DATA_SRC_ID, AUTH_ESSNTL_YN, DOC_DISP_YN, SQL_TEXT, REGID)
VALUES ('A20260509005', '알림 발송',        'NOTIFY','POST', 'sample-notification-send', 'DRAFT', 'DS20260509001', 'Y', 'N', 'CALL sp_send_notification(#{userId}, #{message})', 'seed');

-- 3) API 파라미터
INSERT INTO DXAPI_API_PARAM_M (API_NO, PARAM_SEQ, PARAM_NM, PARAM_TYPE_DVCD, ESSNTL_YN, DESC_TEXT) VALUES ('A20260509001', 1, 'id', 'string', 'Y', '사용자 ID');
INSERT INTO DXAPI_API_PARAM_M (API_NO, PARAM_SEQ, PARAM_NM, PARAM_TYPE_DVCD, ESSNTL_YN)            VALUES ('A20260509002', 1, 'id', 'string', 'Y');
INSERT INTO DXAPI_API_PARAM_M (API_NO, PARAM_SEQ, PARAM_NM, PARAM_TYPE_DVCD, ESSNTL_YN)            VALUES ('A20260509003', 1, 'id', 'string', 'Y');
INSERT INTO DXAPI_API_PARAM_M (API_NO, PARAM_SEQ, PARAM_NM, PARAM_TYPE_DVCD, ESSNTL_YN)            VALUES ('A20260509003', 2, 'subject', 'string', 'Y');
INSERT INTO DXAPI_API_PARAM_M (API_NO, PARAM_SEQ, PARAM_NM, PARAM_TYPE_DVCD, ESSNTL_YN)            VALUES ('A20260509003', 3, 'grade', 'string', 'Y');
INSERT INTO DXAPI_API_PARAM_M (API_NO, PARAM_SEQ, PARAM_NM, PARAM_TYPE_DVCD, ESSNTL_YN)            VALUES ('A20260509005', 1, 'userId', 'string', 'Y');
INSERT INTO DXAPI_API_PARAM_M (API_NO, PARAM_SEQ, PARAM_NM, PARAM_TYPE_DVCD, ESSNTL_YN)            VALUES ('A20260509005', 2, 'message', 'string', 'Y');

-- 4) API 응답 컬럼
INSERT INTO DXAPI_API_RESP_M (API_NO, RSPNS_SEQ, COL_NM, COL_TYPE_DVCD, DISP_NM, MASK_RULE_DVCD) VALUES ('A20260509001', 1, 'user_id', 'VARCHAR', '사용자ID', 'none');
INSERT INTO DXAPI_API_RESP_M (API_NO, RSPNS_SEQ, COL_NM, COL_TYPE_DVCD, DISP_NM, MASK_RULE_DVCD) VALUES ('A20260509001', 2, 'user_nm', 'VARCHAR', '사용자명', 'name');
INSERT INTO DXAPI_API_RESP_M (API_NO, RSPNS_SEQ, COL_NM, COL_TYPE_DVCD, DISP_NM, MASK_RULE_DVCD) VALUES ('A20260509001', 3, 'dept_nm', 'VARCHAR', '부서명', 'none');
INSERT INTO DXAPI_API_RESP_M (API_NO, RSPNS_SEQ, COL_NM, COL_TYPE_DVCD, MASK_RULE_DVCD) VALUES ('A20260509002', 1, 'subject', 'VARCHAR', 'none');
INSERT INTO DXAPI_API_RESP_M (API_NO, RSPNS_SEQ, COL_NM, COL_TYPE_DVCD, MASK_RULE_DVCD) VALUES ('A20260509002', 2, 'grade', 'VARCHAR', 'none');
INSERT INTO DXAPI_API_RESP_M (API_NO, RSPNS_SEQ, COL_NM, COL_TYPE_DVCD, MASK_RULE_DVCD) VALUES ('A20260509002', 3, 'semester', 'VARCHAR', 'none');
INSERT INTO DXAPI_API_RESP_M (API_NO, RSPNS_SEQ, COL_NM, COL_TYPE_DVCD, MASK_RULE_DVCD) VALUES ('A20260509003', 1, 'saved', 'NUMBER', 'none');
INSERT INTO DXAPI_API_RESP_M (API_NO, RSPNS_SEQ, COL_NM, COL_TYPE_DVCD, MASK_RULE_DVCD) VALUES ('A20260509004', 1, 'id', 'VARCHAR', 'none');
INSERT INTO DXAPI_API_RESP_M (API_NO, RSPNS_SEQ, COL_NM, COL_TYPE_DVCD, MASK_RULE_DVCD) VALUES ('A20260509004', 2, 'name', 'VARCHAR', 'none');
INSERT INTO DXAPI_API_RESP_M (API_NO, RSPNS_SEQ, COL_NM, COL_TYPE_DVCD, MASK_RULE_DVCD) VALUES ('A20260509005', 1, 'messageId', 'VARCHAR', 'none');
INSERT INTO DXAPI_API_RESP_M (API_NO, RSPNS_SEQ, COL_NM, COL_TYPE_DVCD, MASK_RULE_DVCD) VALUES ('A20260509005', 2, 'sentAt', 'VARCHAR', 'none');

-- 5) 연계시스템 (인증키 해시는 M3 게이트웨이에서 regenerate-key 로 재발급 — 아래는 자리표시)
INSERT INTO DXAPI_USR_EXT_SYS_M (CONTCT_SYST_ID, CONTCT_SYST_NM, CRTFC_KEY_HASH, CRTFC_KEY_DISTI_TEXT, ALW_IP_ADDR_TEXT, USE_BEGIN_DT, USE_END_DT, PICG_NM, PICG_EMAIL, STTUS_DVCD, REGID)
VALUES ('E20260509001', '학사정보시스템', 'SEED_PLACEHOLDER_REGEN_IN_M3', 'AKAD0001',
        '["10.0.0.0/24","127.0.0.1/32"]',
        TO_TIMESTAMP('2026-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS'),
        TO_TIMESTAMP('2026-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS'),
        '홍길동', 'user01@donga.ac.kr', 'ACTIVE', 'seed');

-- 6) 연계시스템 ↔ API 매핑
INSERT INTO DXAPI_EXT_SYS_API_MAP_M (CONTCT_SYST_ID, API_NO, REGID) VALUES ('E20260509001', 'A20260509001', 'seed');
INSERT INTO DXAPI_EXT_SYS_API_MAP_M (CONTCT_SYST_ID, API_NO, REGID) VALUES ('E20260509001', 'A20260509002', 'seed');

-- 7) 승인 이력 (대기 2건)
INSERT INTO DXAPI_USER_APPR_L (CONFM_SEQ, CONFM_TYPE_DVCD, TARGT_ID, APLCNT_ID, STTUS_DVCD, REASON, APPL_DT, REGID)
VALUES (SEQ_USER_APPR.NEXTVAL, 'USER_SIGNUP', 'user02', 'user02', 'PENDING', '교무처 데이터 분석 업무용 계정 신청',
        TO_TIMESTAMP('2026-05-09 11:20:00','YYYY-MM-DD HH24:MI:SS'), 'seed');
INSERT INTO DXAPI_USER_APPR_L (CONFM_SEQ, CONFM_TYPE_DVCD, TARGT_ID, APLCNT_ID, STTUS_DVCD, REASON, APPL_DT, REGID)
VALUES (SEQ_USER_APPR.NEXTVAL, 'API_USAGE', 'A20260509004', 'E20260509001', 'PENDING', '학사정보시스템 화면에서 조직도 트리 표시를 위해 sample-dept-tree 매핑 요청',
        TO_TIMESTAMP('2026-05-10 08:05:00','YYYY-MM-DD HH24:MI:SS'), 'seed');

COMMIT;
