apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
images:
  - name: harbor.k8s.donga.ac.kr/dau-dx-api/dau-dx-api-mcp
    newTag: 93c4309bfd6c-mcp-fix1
