apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
images:
  - name: harbor.192.168.50.163.nip.io/dev-team/dau-dx-api
    newTag: 978f9af5c5b1-dbfix
